name: deposit_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  auto_route: ^3.2.2
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  intl: ^0.17.0
  currency_text_input_formatter: ^2.1.5
  auto_size_text: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^3.2.1
  flutter_lints: ^1.0.0
  build_runner: ^2.1.7

flutter:
  uses-material-design: true

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Black.ttf
        - asset: assets/fonts/Nunito-Bold.ttf
        - asset: assets/fonts/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito-Light.ttf
        - asset: assets/fonts/Nunito-BlackItalic.ttf
        - asset: assets/fonts/Nunito-BoldItalic.ttf
        - asset: assets/fonts/Nunito-ExtraBold.ttf
        - asset: assets/fonts/Nunito-ExtraLight.ttf
        - asset: assets/fonts/Nunito-Italic.ttf
        - asset: assets/fonts/Nunito-LightItalic.ttf
        - asset: assets/fonts/Nunito-Medium.ttf
        - asset: assets/fonts/Nunito-MediumItalic.ttf
        - asset: assets/fonts/Nunito-SemiBold.ttf
        - asset: assets/fonts/Nunito-SemiBoldItalic.ttf
        - asset: assets/fonts/Nunito-ExtraBoldItalic.ttf
        - asset: assets/fonts/Nunito-ExtraLightItalic.ttf   


